### ISSUE TITLE
IP addresses resolving on Handshake instead of being ignored

### ISSUE THREAD

**Issue by rithvikvibhu** [kyokan/bob-extension#12]
A user on telegram (and probably many others) faced this issue where URLs like https://A.B.C.D/ are caught by the extension and is resolved by Handshake on D/ tld even if A.B.C.D is an IP address.

IP addresses must be ignored here:

https://github.com/kyokan/bob-extension/blob/fc195d209813e9d2fd8fe21345efe9f65d2e0b52/src/background/resolve.ts#L26-L28

**Comment by Falci** [comment]
#13
